### ISSUE TITLE
ReflectionException: Class graftechnology\pdfshift\assetbundles\pdfshift\PdfShiftAsset does not exist

### ISSUE THREAD

**Issue by mach1media** [jacobgraf/pdfshift#9]
Getting an "Internal server error" screen when I go to PDFshift settings.

What's strange is that I don't get this error in my local environment, but I do in production (Arcustech).

This is what the logs show...

2022-07-30 18:52:53 [-][518][ctevjaibrcufns5fk0ro7bkgab][error][yii\di\NotInstantiableException] ReflectionException: Class graftechnology\pdfshift\assetbundles\pdfshift\PdfShiftAsset does not exist in /storage/av07738/www/public_html/vendor/yiisoft/yii2/di/Container.php:507
Stack trace:
#0 /storage/av07738/www/public_html/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#1 /storage/av07738/www/public_html/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#2 /storage/av07738/www/public_html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#3 /storage/av07738/www/public_html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#4 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject()
#5 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle()
#6 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/View.php(294): yii\web\AssetManager->getBundle()
#7 /storage/av07738/www/public_html/vendor/twig/twig/src/Extension/CoreExtension.php(1566): yii\web\View->registerAssetBundle()
#8 /storage/av07738/www/public_html/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#9 /storage/av07738/www/public_html/storage/runtime/compiled_templates/f2/f241a1fc3f998d524637e5720faf7f4cae376c373d1f671a183fc260351361dd.php(46): craft\helpers\Template::attribute()
#10 /storage/av07738/www/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c39b3b55c03651963f56ca08b2acc5061574c39b0309e1508971b99f46ba20e3->doDisplay()
#11 /storage/av07738/www/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#12 /storage/av07738/www/public_html/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#13 /storage/av07738/www/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#14 /storage/av07738/www/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#15 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#16 /storage/av07738/www/public_html/vendor/graftechnology/pdfshift/src/PdfShift.php(115): craft\web\View->renderTemplate()
#17 /storage/av07738/www/public_html/vendor/craftcms/cms/src/base/Plugin.php(212): graftechnology\pdfshift\PdfShift->settingsHtml()
#18 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/View.php(1529): craft\base\Plugin->craft\base\{closure}()
#19 /storage/av07738/www/public_html/vendor/craftcms/cms/src/base/Plugin.php(213): craft\web\View->namespaceInputs()
#20 /storage/av07738/www/public_html/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#21 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings()
#22 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#23 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#24 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#25 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#26 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#27 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest()
#28 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#29 /storage/av07738/www/public_html/public/index.php(22): yii\base\Application->run()
#30 {main}

Next yii\di\NotInstantiableException: Failed to instantiate component or class "graftechnology\pdfshift\assetbundles\pdfshift\PdfShiftAsset". in /storage/av07738/www/public_html/vendor/yiisoft/yii2/di/Container.php:509
Stack trace:
#0 /storage/av07738/www/public_html/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#1 /storage/av07738/www/public_html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#2 /storage/av07738/www/public_html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#3 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject()
#4 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle()
#5 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/View.php(294): yii\web\AssetManager->getBundle()
#6 /storage/av07738/www/public_html/vendor/twig/twig/src/Extension/CoreExtension.php(1566): yii\web\View->registerAssetBundle()
#7 /storage/av07738/www/public_html/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute()
#8 /storage/av07738/www/public_html/storage/runtime/compiled_templates/f2/f241a1fc3f998d524637e5720faf7f4cae376c373d1f671a183fc260351361dd.php(46): craft\helpers\Template::attribute()
#9 /storage/av07738/www/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c39b3b55c03651963f56ca08b2acc5061574c39b0309e1508971b99f46ba20e3->doDisplay()
#10 /storage/av07738/www/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#11 /storage/av07738/www/public_html/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#12 /storage/av07738/www/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#13 /storage/av07738/www/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#14 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render()
#15 /storage/av07738/www/public_html/vendor/graftechnology/pdfshift/src/PdfShift.php(115): craft\web\View->renderTemplate()
#16 /storage/av07738/www/public_html/vendor/craftcms/cms/src/base/Plugin.php(212): graftechnology\pdfshift\PdfShift->settingsHtml()
#17 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/View.php(1529): craft\base\Plugin->craft\base\{closure}()
#18 /storage/av07738/www/public_html/vendor/craftcms/cms/src/base/Plugin.php(213): craft\web\View->namespaceInputs()
#19 /storage/av07738/www/public_html/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#20 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings()
#21 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#22 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#23 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#24 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#25 /storage/av07738/www/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#26 /storage/av07738/www/public_html/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest()
#27 /storage/av07738/www/public_html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#28 /storage/av07738/www/public_html/public/index.php(22): yii\base\Application->run()
#29 {main}

APPLICATION INFO
PHP version	7.4.3
OS version	Linux 5.4.0-97-generic
Database driver & version	MySQL 8.0.29
Image driver & version	Imagick 3.4.4 (ImageMagick 6.9.10-23)
Craft edition & version	Craft Pro 3.7.50
Yii version	2.0.45
Twig version	v2.14.13
Guzzle version	7.4.5

PLUGINS
Inlin	2.1.1
Linkit	3.0.0
Navigation	1.4.28
PdfShift	1.1.1
Reasons	2.3.1
Redactor	2.10.10
Redactor Tweaks	2.0.4
SEOmatic	3.4.37
Site Switcher	2.2.0
vCard	1.2.1

**Comment by RitterKnightCreative** [comment]
@mach1media Bumped into this too. 

The fix for me was to rename the ``vendor/graftechnology/pdfshift/src/assetbundles/PdfShift`` folder to all lowercase (``pdfshift``) and it should start working again.  

Linux is case sensitive while the Mac filesystem (by default) is not.
